import './globals.css'
import { Inter } from 'next/font/google'
import Header2 from '@/components/Navbar/Navbartest'
import Header1 from '@/components/Navbar/Mainnav'

import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header2/>
        {/* <Header1/> */}
        {children}
        <Footer/>
        </body>
    </html>
  )
}
